[Flags]
public enum DamageTypeFlags
{
    AreaEffect,
    AntiInfantry,
    Cluster,
    DirectFireBallistic,
    DirectFireEnergy,
    Electronics,
    HeatCausing,
    Missile,
    OneShot,
    Pulse,
    PointBlank,
    RapidFire,
    SwitchableAmmo,
    VariableDamage,
    Explosive,
}