namespace MegaMekAbstractions.Mechs.Equipment;

/// <summary>
/// Simple weapon implementation used when a specific weapon class does not exist.
/// </summary>
public class GenericWeapon : Weapon
{
    /// <summary>
    /// Initializes a new instance of the <see cref="GenericWeapon"/> class.
    /// </summary>
    /// <param name="name">Name of the weapon.</param>
    /// <param name="criticalSlots">Number of critical slots required.</param>
    /// <param name="tonnage">Tonnage of the weapon.</param>
    /// <param name="heat">Heat generated by the weapon.</param>
    public GenericWeapon(string name, int criticalSlots, decimal tonnage, int heat)
        : base(name, criticalSlots, tonnage, heat, 0, 0, 0, 0, 0, (DamageTypeFlags)0)
    {
    }
}
