namespace MegaMekAbstractions.Mechs.Equipment;

/// <summary>
/// Base class for all mech equipment
/// </summary>
public abstract class MechEquipment
{
    /// <summary>
    /// Gets or sets the equipment name
    /// </summary>
    public required string Name { get; set; }
    
    /// <summary>
    /// Gets or sets the number of critical slots required
    /// </summary>
    public required int CriticalSlots { get; set; }
    
    /// <summary>
    /// Gets or sets the tonnage of the equipment
    /// </summary>
    public required double Tonnage { get; set; }
    
    /// <summary>
    /// Gets or sets the heat generated by the equipment
    /// </summary>
    public int Heat { get; set; }
    
    /// <summary>
    /// Gets or sets the BV (Battle Value) of the equipment
    /// </summary>
    public int BattleValue { get; set; }
    
    /// <summary>
    /// Gets or sets the tech rating of the equipment
    /// </summary>
    public string TechRating { get; set; } = string.Empty;
    
    /// <summary>
    /// Gets or sets whether the equipment is functional
    /// </summary>
    public bool IsFunctional { get; set; } = true;
}

/// <summary>
/// Represents a weapon system
/// </summary>
public class Weapon : MechEquipment
{
    /// <summary>
    /// Gets or sets the weapon's short range
    /// </summary>
    public int ShortRange { get; set; }
    
    /// <summary>
    /// Gets or sets the weapon's medium range
    /// </summary>
    public int MediumRange { get; set; }
    
    /// <summary>
    /// Gets or sets the weapon's long range
    /// </summary>
    public int LongRange { get; set; }
    
    /// <summary>
    /// Gets or sets the weapon's extreme range
    /// </summary>
    public int ExtremeRange { get; set; }
    
    /// <summary>
    /// Gets or sets the weapon's damage
    /// </summary>
    public int Damage { get; set; }
    
    /// <summary>
    /// Gets or sets the ammo count per ton (0 for energy weapons)
    /// </summary>
    public int AmmoPerTon { get; set; }
}

/// <summary>
/// Represents ammunition for weapons
/// </summary>
public class Ammunition : MechEquipment
{
    /// <summary>
    /// Gets or sets the type of ammunition
    /// </summary>
    public required string AmmoType { get; set; }
    
    /// <summary>
    /// Gets or sets the number of shots
    /// </summary>
    public required int ShotsPerTon { get; set; }
}

/// <summary>
/// Represents physical equipment (like MASC, TSM, etc.)
/// </summary>
public class PhysicalWeapon : MechEquipment
{
    /// <summary>
    /// Gets or sets the weapon's damage
    /// </summary>
    public required int Damage { get; set; }
    
    /// <summary>
    /// Gets or sets any special effects or rules
    /// </summary>
    public string SpecialEffect { get; set; } = string.Empty;
}
