namespace MegaMekAbstractions.Mechs.Equipment;

/// <summary>
/// Base class for all mech equipment
/// </summary>
public abstract class MechEquipment
{
    /// <summary>
    /// Gets or sets the equipment name
    /// </summary>
    public string Name { get; protected set; }

    /// <summary>
    /// Gets or sets the number of critical slots required
    /// </summary>
    public int CriticalSlots { get; protected set; }

    /// <summary>
    /// Gets or sets the tonnage of the equipment
    /// </summary>
    public decimal Tonnage { get; protected set; }

    /// <summary>
    /// Gets or sets the heat generated by the equipment
    /// </summary>
    public int Heat { get; protected set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="MechEquipment"/> class.
    /// </summary>
    /// <param name="name">The name of the equipment.</param>
    /// <param name="criticalSlots">The number of critical slots required.</param>
    /// <param name="tonnage">The tonnage of the equipment.</param>
    /// <param name="heat">The heat generated by the equipment.</param>
    protected MechEquipment(string name, int criticalSlots, decimal tonnage, int heat)
    {
        Name = name;
        CriticalSlots = criticalSlots;
        Tonnage = tonnage;
        Heat = heat;
    }
}
