name: Publish NuGet Packages

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for release (e.g., v1.1.1)'
        required: true
        type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Pack MegaMekAbstractions
      run: dotnet pack MegaMekAbstractions/MegaMekAbstractions.csproj -c Release -o packages
      
    - name: Pack MegaMekParser.Mtf
      run: dotnet pack MegaMekParser.Mtf/MegaMekParser.Mtf.csproj -c Release -o packages
      
    - name: Push packages
      run: dotnet nuget push packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
